Construccion.WEBUI/Construccion.WEBUI/Controllers/ChartsController.cs
using Construccion.WEBUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Controllers
{

    public class ChartsController : Controller
    {
        private readonly HttpClient _httpClient;
        public ChartsController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public IActionResult Index()
        {
            var UserName = HttpContext.Session.GetString("user_Nombre");
            if (UserName != "" && UserName != null)
            {
                ViewBag.Admin = HttpContext.Session.GetString("user_EsAdmin");
                ViewBag.Nombre = HttpContext.Session.GetString("empl_Nombre");
                ViewBag.Mensaje = HttpContext.Session.GetString("Mensaje");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EmpleadosChart()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Empleados/EmpleadosPorSexo");
            if (response.IsSuccessStatusCode)
            {
                string res = await response.Content.ReadAsStringAsync();
                var respuestaX = JsonConvert.DeserializeObject<EmpleadosChartViewModel>(res);
                return Json(respuestaX);

            }
            return View();
        }

        [HttpGet]

        public async Task<IActionResult> InsumosChart()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Insumos/InsumosMasUtilizados");
            if (response.IsSuccessStatusCode)
            {
                string res = await response.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<InsumosMasUtilizadosChart>>(res);
                return Json(data);

            }
            return View();
        }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Views/Charts/Index.cshtml
<div class="row mt-2">

    <div class="col-sm-6">
        <div class="card">
            <div class="card-header" style="background-color:#ffbd26"><h3><strong>Cantidad de Empleados por Sexo</strong></h3></div>
            <div class="card-body">
                <canvas id="EmpleadosChart" style="max-height:260px"></canvas>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header" style="background-color:#ffbd26"><h3><strong>Insumos más Utilizados</strong></h3></div>
            <div class="card-body">
                <canvas id="InsumosChart" style="max-height:260px"></canvas>
            </div>
        </div>
    </div>
</div>
    <script>
    $(function () { 
        $.ajax({
            type: 'GET',
            url: '@Url.Action("EmpleadosChart", "Charts")',
            success: function (data) {
                var chartData = {
                    labels: data.labels,
                    datasets: [
                        {
                            data: data.data,
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.6)',
                                'rgba(54, 162, 235, 0.6)'
                            ]
                        }
                    ]
                };

                var options = {
                    tooltips: {
                        callbacks: {
                            label: function (tooltipItem, data) {
                                var dataset = data.datasets[tooltipItem.datasetIndex];
                                var total = dataset.data.reduce(function (previousValue, currentValue, currentIndex, array) {
                                    return previousValue + currentValue;
                                });
                                var currentValue = dataset.data[tooltipItem.index];
                                var percentage = Math.floor(((currentValue / total) * 100) + 0.5);
                                return percentage.toLocaleString() + "%";
                            }
                        }
                    }
                };

                var ctx = document.getElementById('EmpleadosChart').getContext('2d');
                var empleadosChart = new Chart(ctx, {
                    type: 'pie',
                    data: chartData,
                    options: options
                });
            },
            error: function () {
                alert('Error al obtener los datos');
            }
        });
    });
        $(function () {
            $.ajax({
                url: '/Charts/InsumosChart',
                type: 'GET',
                dataType: 'json',
                success: function (response) {
                    var nombresInsumos = [];
                    var cantidadesUsos = [];
                    response.forEach(function (insumo) {
                        nombresInsumos.push(insumo.nombre);
                        cantidadesUsos.push(insumo.cantidadDeUsos);
                    });
                    var chartdata = {
                        labels: nombresInsumos,
                        datasets: [
                            {
                                label: 'Cantidad de usos',
                                backgroundColor: 'rgba(255, 206, 86, 0.6)',
                                borderColor: 'rgba(255, 206, 86, 1)',
                                hoverBackgroundColor: 'rgba(200, 200, 200, 1)',
                                hoverBorderColor: 'rgba(200, 200, 200, 1)',
                                data: cantidadesUsos
                            }
                        ]
                    };
                    var ctx = $("#InsumosChart");
                    var barGraph = new Chart(ctx, {
                        type: 'bar',
                        data: chartdata
                    });
                },
                error: function (response) {
                    console.log(response);
                }
            });
        });
    </script>