Construccion.WEBUI/Construccion.WEBUI/Models/IncidenciasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Models
{
    public class IncidenciasViewModel
    {
        [Display(Name = "ID")]
        public int inci_Id { get; set; }

        [Display(Name = "Construcción")]
        public int cons_Id { get; set; }

        [Display(Name = "Construcción")]
        [NotMapped]
        public string cons_Proyecto { get; set; }

        [Display(Name = "Incidencia")]
        public string inci_Descripcion { get; set; }
        public int? user_UsuCreacion { get; set; }
        public DateTime inci_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? inci_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Controllers/IncidenciasController.cs
using Construccion.WEBUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Controllers
{
    public class IncidenciasController : Controller
    {
        private readonly HttpClient _httpClient;

        public IncidenciasController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public async Task<IActionResult> Index()
        {
            var UserName = HttpContext.Session.GetString("user_Nombre");
            if (UserName != "" && UserName != null)
            {
                ViewBag.Admin = HttpContext.Session.GetString("user_EsAdmin");
                ViewBag.Nombre = HttpContext.Session.GetString("empl_Nombre");
                ViewBag.Mensaje = HttpContext.Session.GetString("Mensaje");
                var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Incidencias/List");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<ResponseAPI<IncidenciasViewModel>>(content);
                var res = result.data;
                return View(res);
            }
            else
            {
                // manejar error
                return null;
            }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(IncidenciasViewModel incidenciasView, string inci_Descripcion, int cons_Id)
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            incidenciasView.user_UsuCreacion = HttpContext.Session.GetInt32("UsuarioId");
            HttpResponseMessage response = await _httpClient.PostAsJsonAsync<IncidenciasViewModel>(builder.GetSection("ApiSettings:baseUrl").Value + "Incidencias/Insert", incidenciasView);

            if (response.IsSuccessStatusCode)
            {
                string res = await response.Content.ReadAsStringAsync();
                var respuestaX = JsonConvert.DeserializeObject<INSERTAPI>(res);
                var mensaje = respuestaX.message;
                HttpContext.Session.SetString("NombreUsuario", mensaje);
                return RedirectToAction("Index");
            }
            return View();
        }




        [HttpGet("/Incidencias/ListarConstrucciones")]

        public async Task<IActionResult> ListarConstrucciones()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Incidencias/ListadoConstrucciones");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var construcciones = JsonConvert.DeserializeObject<List<ListarConstrucciones>>(content);
                return Json(construcciones);
            }
            else
            {
                // manejar error
                return null;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IncidenciasViewModel incidencias)
        {
            incidencias.user_UsuModificacion = (int)HttpContext.Session.GetInt32("UsuarioId");
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            var proveedorJson = new StringContent(JsonConvert.SerializeObject(incidencias), Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Incidencias/Update", proveedorJson);


            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                var respuesta = JsonConvert.DeserializeObject<INSERTAPI>(content);

                ViewBag.Success = respuesta.message;

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        [HttpPost("/Incidencias/EliminarIncidencias")]
        public async Task<IActionResult> EliminarUsuario(int inci_Id)
        {
            var Usuario_Id = HttpContext.Session.GetInt32("UsuarioId");
            IncidenciasViewModel incidenciasView = new IncidenciasViewModel();
            incidenciasView.user_UsuModificacion = Usuario_Id;
            incidenciasView.inci_Id = inci_Id;
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.PostAsJsonAsync<IncidenciasViewModel>(builder.GetSection("ApiSettings:baseUrl").Value + "Incidencias/EliminarIncidencia", incidenciasView);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<INSERTAPI>(content);
                var res = result.message;
                return Json(1);
            }
            return Json(0);
        }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Views/Incidencias/Index.cshtml
@model IEnumerable<Construccion.WEBUI.Models.IncidenciasViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 mb-0 order-0">
    <div class="card" style="background-color: white">
        <div class="d-flex align-items-end row">
            <div class="col-sm-12">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <img src="~/Content/images/ACROPOLIS-LOGO.png" width="200" />
                        <h3 style="color:black"><strong>Listado de Incidencias</strong></h3>
                    </div>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" onclick="AbrirModalCrearIncidencia()"><i class="fa fa-plus-square"></i> Nuevo</a>
                    <br />
                    <br />
                    <table class="table table-responsive table-report -mt-2" id="DataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.inci_Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.cons_Proyecto)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.inci_Descripcion)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.inci_Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.cons_Proyecto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.inci_Descripcion)
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#EditarCargo" onclick="Editar('@item.inci_Id,@item.inci_Descripcion')"><i class="fa fa-edit"></i> Editar</a>

                                    </td>
                                    <td>
                                        <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#DeleteIncidencia" onclick="Preliminar('@item.inci_Id')"><i class="fa fa-trash"></i> Eliminar</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
    <partial name="_Create">
    @Html.Partial("_Edit", new Construccion.WEBUI.Models.IncidenciasViewModel())
    <partial name="_EliminarIncidencia" />
    <script src="~/js/Incidencias/CreateIncidencias.js"></script>

Construccion.WEBUI/Construccion.WEBUI/Views/Incidencias/_Create.cshtml
<Form action="@Url.Action("Create","Incidencias")" method="post" id="createincidencias">

    <div class="modal fade" id="CreateIncidencias" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <h3 style="color:black"><strong>Nueva Incidencia</strong></h3>
                    </div>
                </div>
                <div class="modal-body">
                    <br />
                    <div class="row">
                        <div class="col-sm-6">
                            <label class="text-danger">*</label>
                            <label>Incidencia</label>
                            <input type="text" id="inci_Descripcion" name="inci_Descripcion" class="form-control" />
                            <br />
                        </div>
                        <div class="col-sm-6">
                            <label class="text-danger">*</label>
                            <label>Construccion</label>
                            <select id="cons_Id" name="cons_Id" class="form-control" style="text-align-last:center">
                            </select>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" data-bs-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarInsert()" class="btn btn-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</Form>
<script>

    function GuardarInsert() {

        var siuu = true;


        if ($('#inci_Descripcion').val() == "") {
            siuu = false;

        }

        if ($("#cons_Id").val() == "") {
            siuu = false;
        }

        if (!siuu) {
            mostrarErrorToast("Campos requeridos.");
        }

        if (siuu) {
            $('#createincidencias').submit();
        }

    };

</script>

Construccion.WEBUI/Construccion.WEBUI/Views/Incidencias/_Edit.cshtml
@model Construccion.WEBUI.Models.IncidenciasViewModel
<!-- Modal-->
<div class="modal fade" id="EditarIncidencia" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="card-header" style="background-color:#ffbd26">
                <div class="text-center">
                    <h3 style="color:black"><strong>Editar Incidencia</strong></h3>
                </div>
            </div>
            <div class="modal-body">
                <form asp-action="Edit" id="IncidenciasEditar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input asp-for="inci_Id" id="car_IDEdit" hidden class="form-control" />

                            <label asp-for="inci_Descripcion" class="control-label"></label>
                            <input asp-for="inci_Descripcion" id="car_DescripcionEditar" class="form-control" />
                            <div class="text-center">
                                <span id="car_DescripcionValidateEdit" class="text-danger" hidden><strong>Campo requerido</strong></span>
                            </div>
                        </div>
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="CerraLimpiar()" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" onclick="GuardarEdit()" class="btn btn-secondary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>
function CerraLimpiar() {
        $('#car_DescripcionEditar').val("");
        $('#EditarIncidencia').modal('hide');
        $('#car_DescripcionValidateEdit').attr('hidden', true);

    }

    function Editar(cadena) {
        var datastring = cadena;
        var data = datastring.split(',');
        $("#car_IDEdit").val(data[0]);
        $("#car_DescripcionEditar").val(data[1]);
        $("#EditarIncidencia").modal('show');
    };

    function GuardarEdit() {


        if ($('#car_DescripcionEditar').val() == "") {
            $('#car_DescripcionValidateEdit').attr('hidden', false)

        }


        if ($('#car_DescripcionEditar').val() == "") {
            mostrarErrorToast("Campos requeridos.");

        }

        else{
            $('#IncidenciasEditar').submit();
        }


    };</script>

Construccion.WEBUI/Construccion.WEBUI/Views/Incidencias/_EliminarIncidencia.cshtml
<div class="modal fade" id="DeleteIncidencia" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content bg-danger text-white">
            <div class="modal-body text-center">
                <h3 class="text-white mb-15"><i class="fa fa-exclamation-triangle"></i> Alert</h3>
                <input type="hidden" id="txtIncidenciaEliminar" name="inci_Id" />
                <div class="text-gray-600 mt-2">
                    ¿Está seguro de eliminar el registro?
                    <br />
                    <br />
                    <button type="button" data-dismiss="modal" class="btn btn-default">Salir</button>
                    <button type="button" id="confirmar" class="btn btn-primary" onclick="EliminarUsuario()">Eliminar</button>
                </div>
            </div>
        </div>
    </div>
</div>