Construccion.WEBUI/Construccion.WEBUI/Models/CargosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Models
{
    public class CargosViewModel
    {
        [Display(Name = "Cargo Id")]
        public int carg_Id { get; set; }

        [Display(Name = "Cargo")]
        public string carg_Cargo { get; set; }

        [Display(Name = "Usuario Creación")]
        public int? user_UsuCreacion { get; set; }

        [Display(Name = "Fecha Creación")]
        public DateTime carg_FechaCreacion { get; set; }

        [Display(Name = "Usuario Modificación")]
        public int? user_IdModificacion { get; set; }

        [Display(Name = "Fecha Modificación")]
        public DateTime? carg_FechaModificacion { get; set; }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Controllers/CargosController.cs
using Construccion.WEBUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Controllers
{
    public class CargosController : Controller
    {
        private readonly HttpClient _httpClient;

        public CargosController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> Index()
        {
            var UserName = HttpContext.Session.GetString("user_Nombre");
            if (UserName != "" && UserName != null)
            {
                ViewBag.Admin = HttpContext.Session.GetString("user_EsAdmin");
                ViewBag.Nombre = HttpContext.Session.GetString("empl_Nombre");
                ViewBag.Mensaje = HttpContext.Session.GetString("Mensaje");
                var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Cargos/List");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<ResponseAPI<CargosViewModel>>(content);
                var res = result.data;
                return View(res);
            }
            else
            {
                // manejar error
                return null;
            }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CargosViewModel cargosViewModel, string carg_Cargo)
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            cargosViewModel.user_UsuCreacion = HttpContext.Session.GetInt32("UsuarioId");
            HttpResponseMessage response = await _httpClient.PostAsJsonAsync<CargosViewModel>(builder.GetSection("ApiSettings:baseUrl").Value + "Cargos/Insert", cargosViewModel);

            if (response.IsSuccessStatusCode)
            {
                string res = await response.Content.ReadAsStringAsync();
                var respuestaX = JsonConvert.DeserializeObject<INSERTAPI>(res);
                var mensaje = respuestaX.message;
                HttpContext.Session.SetString("NombreUsuario", mensaje);
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Edit(CargosViewModel cargosViewModel)
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();

            var proveedorJson = new StringContent(JsonConvert.SerializeObject(cargosViewModel), Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Cargos/Update", proveedorJson);


            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                var respuesta = JsonConvert.DeserializeObject<INSERTAPI>(content);

                ViewBag.Success = respuesta.message;

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Views/Cargos/Index.cshtml
@model IEnumerable<Construccion.WEBUI.Models.CargosViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 mb-0 order-0">
    <div class="card" style="background-color: white">
        <div class="d-flex align-items-end row">
            <div class="col-sm-12">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <img src="~/Content/images/ACROPOLIS-LOGO.png" width="200" />
                        <h3 style="color:black"><strong>Listado de Cargos</strong></h3>
                    </div>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#CreateCargos"><i class="fa fa-plus-square"></i>  Nuevo</a>
                    <br />
                    <br />
                    <table class="table table-report -mt-2" id="DataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.carg_Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.carg_Cargo)
                                </th>
                                <th>
                                    <div class="text-center">Editar</div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.carg_Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.carg_Cargo)
                                    </td>
                                    <td>
                                        <div class="text-center">
                                            <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#EditarCargo" onclick="Editar('@item.carg_Id,@item.carg_Cargo')"><i class="fa fa-edit"></i> Editar</a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
<br />
<partial name="_Create">
@Html.Partial("_Edit", new Construccion.WEBUI.Models.CargosViewModel())

Construccion.WEBUI/Construccion.WEBUI/Views/Cargos/_Create.cshtml
<Form action="@Url.Action("Create","Cargos")" method="post" id="createcargos">

    <div class="modal fade" id="CreateCargos" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <h3 style="color:black"><strong>Nuevo Cargo</strong></h3>
                    </div>
                </div>
                <div class="modal-body">
                    <br />
                    <label class="text-danger">*</label>
                    <label>Descripción</label>
                    <input type="text" id="carg_Cargo" name="carg_Cargo" class="form-control" />
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" data-bs-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarInsert()" class="btn btn-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</Form>
<script>

    function GuardarInsert() {

        var siuu = true;


        if ($('#carg_Cargo').val() == "") {
            mostrarErrorToast("Campos requeridos.");
            siuu = false;

        }

        if (siuu) {
            $('#createcargos').submit();
        }

    };

</script>

Construccion.WEBUI/Construccion.WEBUI/Views/Cargos/_Edit.cshtml
@model Construccion.WEBUI.Models.CargosViewModel
<!-- Modal-->
<div class="modal fade" id="EditarCargo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="card-header" style="background-color:#ffbd26">
                <div class="text-center">
                    <h3 style="color:black"><strong>Editar Cargo</strong></h3>
                </div>
            </div>
            <div class="modal-body">
                <form asp-action="Edit" id="CargosEditar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div>
                        <div>
                            <input asp-for="carg_Id" id="car_IDEdit" hidden class="form-control" />
                            <label asp-for="carg_Cargo" class="control-label"></label>
                            <input asp-for="carg_Cargo" id="car_DescripcionEditar" class="form-control" />
                            <div class="text-center">
                                <span id="car_DescripcionValidateEdit" class="text-danger" hidden><strong>Campo requerido</strong></span>
                            </div>
                        </div>
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="CerraLimpiar()" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" onclick="GuardarEdit()" class="btn btn-secondary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>function CerraLimpiar() {
        $('#car_DescripcionEditar').val("");
        $('#EditarCargo').modal('hide');
        $('#car_DescripcionValidateEdit').attr('hidden', true);

    }

    function Editar(cadena) {
        var datastring = cadena;
        var data = datastring.split(',');
        $("#car_IDEdit").val(data[0]);
        $("#car_DescripcionEditar").val(data[1]);
        $("#EditarCargo").modal('show');
    };

    function GuardarEdit() {


        if ($('#car_DescripcionEditar').val() == "") {
            $('#car_DescripcionValidateEdit').attr('hidden', false)

        }


        if ($('#car_DescripcionEditar').val() == "") {
            mostrarErrorToast("Campos requeridos.");

        }

        else{
            $('#CargosEditar').submit();
        }


    };</script>