Construccion.WEBUI/Construccion.WEBUI/Models/InsumosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Models
{
    public class InsumosViewModel
    {
        [Display(Name = "Id")]
        public int insm_Id { get; set; }

        [Display(Name = "Insumo")]
        public string insm_Descripcion { get; set; }

        [Display(Name = "Unidad de Medida")]
        public int unim_Id { get; set; }

        [Display(Name = "Unidades de Medida")]
        public int user_UsuCreacion { get; set; }

        [Display(Name = "Fecha Creación")]
        public DateTime insm_FechaCreacion { get; set; }

        [Display(Name = "Usuario Modificación")]
        public int? user_UsuModificacion { get; set; }

        [Display(Name = "Fecha de Modificación")]
        public DateTime? insm_FechaModificacion { get; set; }

        [NotMapped]
        [Display(Name = "Unidad de Medida")]
        public string unim_Descripcion { get; set; }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Controllers/InsumosController.cs
using Construccion.WEBUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace Construccion.WEBUI.Controllers
{
    public class InsumosController : Controller
    {
        private readonly HttpClient _httpClient;

        public InsumosController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public async Task<IActionResult> Index()
        {
            var UserName = HttpContext.Session.GetString("user_Nombre");
            if (UserName != "" && UserName != null)
            {
                ViewBag.Admin = HttpContext.Session.GetString("user_EsAdmin");
                ViewBag.Nombre = HttpContext.Session.GetString("empl_Nombre");
                ViewBag.Mensaje = HttpContext.Session.GetString("Mensaje");
                var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
                HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Insumos/List");
                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<ResponseAPI<InsumosViewModel>>(content);
                    var res = result.data;
                    return View(res);
                }
                else
                {
                    // manejar error
                    return null;
                }
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public async Task<IActionResult> Create(InsumosViewModel insumosView, string insm_Descripcion, int unim_Id)
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            insumosView.user_UsuCreacion = (int)HttpContext.Session.GetInt32("UsuarioId");
            HttpResponseMessage response = await _httpClient.PostAsJsonAsync<InsumosViewModel>(builder.GetSection("ApiSettings:baseUrl").Value + "Insumos/Insert", insumosView);

            if (response.IsSuccessStatusCode)
            {
                string res = await response.Content.ReadAsStringAsync();
                var respuestaX = JsonConvert.DeserializeObject<INSERTAPI>(res);
                var mensaje = respuestaX.message;
                HttpContext.Session.SetString("NombreUsuario", mensaje);
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Edit(InsumosViewModel insumos)
        {

            insumos.user_UsuModificacion = (int)HttpContext.Session.GetInt32("UsuarioId");
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            var proveedorJson = new StringContent(JsonConvert.SerializeObject(insumos), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Insumos/Update", proveedorJson);

            

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                var respuesta = JsonConvert.DeserializeObject<INSERTAPI>(content);

                ViewBag.Success = respuesta.message;

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        [HttpGet("/Insumos/CargarUnidadesMedida")]

        public async Task<IActionResult> CargarUnidadesMedida()
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            HttpResponseMessage response = await _httpClient.GetAsync(builder.GetSection("ApiSettings:baseUrl").Value + "Insumos/ListarUnidadesdeMedida");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var unidadesMedida = JsonConvert.DeserializeObject<List<DDLUnidadesMedida>>(content);
                return Json(unidadesMedida);
            }
            else
            {
                // manejar error
                return null;
            }
        }
    }
}

Construccion.WEBUI/Construccion.WEBUI/Views/Insumos/Index.cshtml
@model IEnumerable<Construccion.WEBUI.Models.InsumosViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 mb-0 order-0">
    <div class="card" style="background-color: white">
        <div class="d-flex align-items-end row">
            <div class="col-sm-12">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <img src="~/Content/images/ACROPOLIS-LOGO.png" width="200" />
                        <h3 style="color:black">
                            <strong>Listado de Insumos</strong>
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-5">
                            <a class="btn btn-primary" onclick="AbrirModalCrearInsumos()"><i class="fa fa-plus-square"></i> Nuevo</a>
                        </div>
                        <div class="col-sm-5">
                            <a class="btn btn-defaults" href="/CreatePDF/ReporteInsumos">
                                <div class="d-flex align-items-center">
                                    <span class="nav-link-icon">
                                        <span>
                                            <i class="fa fa-file-text"></i>
                                        </span>
                                    </span>
                                    <span class="nav-link-text ps-1">Reporte</span>
                                </div>
                            </a>
                        </div>
                    </div>
                    <br />
                    <br />
                    <table class="table table-report -mt-2" id="DataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.insm_Id)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.insm_Descripcion)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.unim_Descripcion)
                                </th>
                                <th>
                                    Editar
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.insm_Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.insm_Descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.unim_Descripcion)
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#EditarCargo" onclick="Editar('@item.insm_Id,@item.insm_Descripcion')"><i class="fa fa-edit"></i> Editar</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<partial name="_Create" />
@Html.Partial("_Edit", new Construccion.WEBUI.Models.InsumosViewModel())
<script src="~/js/Insumos/CreateInsumos.js"></script>

Construccion.WEBUI/Construccion.WEBUI/Views/Insumos/_Create.cshtml
<Form action="@Url.Action("Create","Insumos")" method="post" id="createinsumos">

    <div class="modal fade" id="CreateInsumos" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffbd26">
                    <div class="text-center">
                        <h3 style="color:black"><strong>Nuevo Insumo</strong></h3>
                    </div>
                </div>
                <div class="modal-body">
                    <br />
                    <div class="row">
                        <div class="col-sm-6">
                            <label class="text-danger">*</label>
                            <label>Descripción</label>
                            <input type="text" id="insm_Descripcion" name="insm_Descripcion" class="form-control" />
                            <br />
                        </div>
                        <div class="col-sm-6">
                            <label class="text-danger">*</label>
                            <label>Unidad de Medida</label>
                            <select id="unim_Id" name="unim_Id" class="form-control"  style="text-align-last:center">
                            </select>
                        </div>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button type="button" data-bs-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarInsert()" class="btn btn-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</Form>
<script>

    function GuardarInsert() {

        var siuu = true;


        if ($('#insm_Descripcion').val() == "") {
            siuu = false;

        }

        if ($("#unim_Id").val() == "") {
            siuu = false;
        }

        if (!siuu) {
            mostrarErrorToast("Campos requeridos.");
        }

        if (siuu) {
            $('#createinsumos').submit();
        }

    };

</script>

Construccion.WEBUI/Construccion.WEBUI/Views/Insumos/_Edit.cshtml
@model Construccion.WEBUI.Models.InsumosViewModel
<!-- Modal-->
<div class="modal fade" id="EditarInsumo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="card-header" style="background-color:#ffbd26">
                <div class="text-center">
                    <h3 style="color:black"><strong>Editar Cargo</strong></h3>
                </div>
            </div>
            <div class="modal-body">
                <form asp-action="Edit" id="InsumosEditar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input asp-for="insm_Id" id="car_IDEdit" hidden class="form-control" />
                            <label asp-for="insm_Descripcion" class="control-label"></label>
                            <input asp-for="insm_Descripcion" id="car_DescripcionEditar" class="form-control" />
                            <div class="text-center">
                                <span id="car_DescripcionValidateEdit" class="text-danger" hidden><strong>Campo requerido</strong></span>
                            </div>
                        </div>
                    </div>


                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="CerraLimpiar()" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" onclick="GuardarEdit()" class="btn btn-secondary">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script>






    function CerraLimpiar() {
        $('#car_DescripcionEditar').val("");
        $('#EditarCargo').modal('hide');
        $('#car_DescripcionValidateEdit').attr('hidden', true);

    }



    function Editar(cadena) {
        var datastring = cadena;
        var data = datastring.split(',');
        $("#car_IDEdit").val(data[0]);
        $("#car_DescripcionEditar").val(data[1]);
        $("#EditarInsumo").modal('show');
    };
    function GuardarEdit() {


        if ($('#car_DescripcionEditar').val() == "") {
            $('#car_DescripcionValidateEdit').attr('hidden', false)

        }

        if ($('#car_DescripcionEditar').val() == "") {
            mostrarErrorToast("Campos requeridos.");

        }

        else{
            $('#InsumosEditar').submit();
        }


    };
</script>